---
# Playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Get file status for /opt/ghidra/Ghidra/application.properties
    stat:
      path: /opt/ghidra/Ghidra/application.properties
    register: ghidra_properties_file

  - name: Assert that file exists and is a regular file
    assert:
      that:
        - ghidra_properties_file.stat.exists
        - ghidra_properties_file.stat.isreg
